export const ERROR_CODE = {

    // RESOURCE
    RESOURCE_NOT_FOUND: "RESOURCE_001",
    OTP_SEND_LIMIT_EXCEEDED: "RESOURCE_002",

    // USER
    USER_NOT_FOUND: "USER_001",
    USER_EXISTS: "USER_002",
    // AUTH
    UNAUTHORIZED: "AUTH_001",
    FORBIDDEN: "AUTH_002",
    TOKEN_EXPIRED : "AUTH_003",

    // VALIDATION
    VALIDATION_ERROR: "VALIDATION_001",
    INVALID_ID_ERROR: "VALIDATION_002",
    INVALID_INPUT_ERROR: "VALIDATION_003",
    DUPLICATE_ITEMS: "VALIDATION_004",

    // CONFLICT
    CONFLICT_ERROR: "CONFLICT_001",
    CONFLICT_INPUT_ERROR: "CONFLICT_002",
    INSUFFICIENT_STOCK: "CONFLICT_003",

    // TIMEOUT
    REQUEST_TIMEOUT_ERROR: "TIMEOUT_001",


    // COMMON
    COMMON_ERROR: "COMMON_001",

    // INTERNAL
    INTERNAL_ERROR: "INTERNAL_001",
    TRANSACTION_ERROR: "INTERNAL_002",

} as const;

export type ErrorCode = typeof ERROR_CODE[keyof typeof ERROR_CODE];