export const INJECTION_TOKEN = {
    REDIS_CLIENT: 'REDIS_CLIENT',

    // Repositories
    USER_REPOSITORY: 'USER_REPOSITORY',
    SESSION_REPOSITORY: 'SESSION_REPOSITORY',
    OAUTH_PROVIDER_REPOSITORY: 'OAUTH_PROVIDER_REPOSITORY',
} as const;
